### PR TITLE
Fix(omen_contracts): update kleros proxy deployment

### PR DESCRIPTION
**Pull request by alcercu**
As mentioned in issue #495, the script in charge of loading dispute metadata in the kleros proxy that was being used could have problems loading. This fix changes the address to a new proxy recently deployed, here are the details:

- Old `homeProxy`: https://gnosisscan.io/address/0x29f39de98d750eb77b5fafb31b2837f079fce222
- New `homeProxy`: https://gnosisscan.io/address/0x5562ac605764dc4039fb6ab56a74f7321396cdf2
- reality.eth test question: https://reality.eth.limo/app/index.html#!/network/100/question/0x79e32ae03fb27b07c89c0c568f80287c01ca2e57-0x31c16666a9a5482f71b02b9ebbe8cfbb38eb1631e3de55488db0dca283d3a55a/token/XDAI
- Kleros dispute for the reality.eth question: https://court.kleros.io/cases/1654 (mainnet)

If you have any question or requested change, don't hesitate to ask!

### CODE REVIEW

**Comment by kongzii** [comment]
Hi @alcercu , thanks a lot! Sorry for the late response, I'm on DevCon this week.

I see there is still the `We do not recognize this arbitrator. Do not believe this information unless you trust them` message on Reality, is this something you can fix or should I ask someone from Reality?

And second question, this should be changed also in Olas' market creator, do you want to contribute there as well, or should I? See https://github.com/valory-xyz/market-creator/pull/120/files.

**Comment by alcercu** [comment]
hello @kongzii! No worries, same here. We were all at devcon 🙌🏻 
Regarding your first question, we already messaged Reality's maintainer to add it, will ping here when it's added.
As for the second point, yes please, feel free to create the PR in Olas if it's needed. But please tag this issue/me so I can keep track 🫡

**Comment by kongzii** [comment]
Cool thanks! Then I'll wait and once it's set up on Reality, I'll merge this + create it in Olas.

**Comment by alcercu** [comment]
Hey @kongzii! The arbitrator has been added to Reality 🙌🏻 https://github.com/RealityETH/reality-eth-monorepo/commit/23b662b86d40c49a9f319f9cce8ad74a467099b1
image

**Comment by kongzii** [comment]
Nice, thanks!

**Comment by kongzii** [comment]
Pipelines will error out as credentials are missing in fork PRs, but this change shouldn't bring any problems so will just merge 🤞

**Comment by unknownunknown1** [comment]
@kongzii Hi, since the new proxy has been added to Reality UI we'd like to test the whole flow starting with Omen markets -> Reality -> Reality proxy -> Kleros Court. Is Omen UI ready so we can create a test question with it?

**Comment by kongzii** [comment]
Hey @unknownunknown1 , it's not possible to create markets on Presagio/Ommen UI yet, but I can create it for you, just let me know the details. Or you can use [this](https://github.com/gnosis/prediction-market-agent-tooling/blob/main/scripts/create_market_omen.py) script if you want to do it yourself.

**Comment by unknownunknown1** [comment]
Hi, @kongzii If the Omen UI is not ready and requires some manual work maybe we should wait until it's ready before doing the final test so it's more relevant. What do you think?

**Comment by kongzii** [comment]
@unknownunknown1 Markets are being created daily by agents, so it's already possible that someone will want to ask for arbitration on Kleros. Because we merged this, some markets will be also created with this new arbitrator address. 

I think it's worth trying it, if we aren't sure that it works. 🤔

**Comment by unknownunknown1** [comment]
Ok, then. Can you please either create a new market for test purposes, or link me a Reality question of the existing market so I can challenge it and take it to KlerosCourt? The market should have a new proxy as an arbitrator. And can you please also give me the link to the market related to the question too?

**Comment by kongzii** [comment]
Sure! Here

- https://presagio.pages.dev/markets?id=0x0b0edc42698ec1f4bd4bfed89405dbd3429f1d0f 
- https://reality.eth.limo/app/#!/network/100/question/0x79e32ae03fb27b07c89c0c568f80287c01ca2e57-0x08f805ce5292918e9d2f900c2a3ddd97ac17eafa9d9f387eafffbb1732742ba2/token/XDAI

The question will open in 30 min.

**Comment by unknownunknown1** [comment]
Thanks, one thing though. When we test we usually simulate a real environment, as if it's a question that can be challenged and go to court, so we can also test's juror's perception of it. Is there an existing market that uses new proxy and is open or soon-to-be-open?

**Comment by kongzii** [comment]
Not yet, there will be after we deploy it (https://github.com/gnosis/prediction-market-agent/pull/560), so probably tomorrow. Or if you can tell me any questions (even duplicate with existing ones), I can create that/.

**Comment by unknownunknown1** [comment]
@kongzii Can you please use this question?
"Will George Russell win the FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX 2024?"

**Pull request merged**
